<?php 
$t = {
    "id":16557,     
    "parent_id":0,     
    "number":"16557",     
    "order_key":"wc_order_FYs43FkFiN4m4",     
    "created_via":"checkout",     
    "version":"4.0.1",
    "status":"on-hold",
    "currency":"GEL",
    "date_created":"2020-05-01T14:26:05",
    "date_created_gmt":"2020-05-01T10:26:05",
    "date_modified":"2020-05-01T14:26:05",
    "date_modified_gmt":"2020-05-01T10:26:05",
    "discount_total":"0.00",
    "discount_tax":"0.00",
    "shipping_total":"0.00",
    "shipping_tax":"0.00",
    "cart_tax":"0.00",
    "total":"42.50",
    "total_tax":"0.00",
    "prices_include_tax":true,
    "customer_id":1,
    "customer_ip_address":"176.221.239.92",
    "customer_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,      like Gecko) Chrome/81.0.4044.129 Safari/537.36",
    "customer_note":"sdfgs dfgsdfg wsergwertwert w ert wer",
    "billing":{"first_name":"Test",
        "last_name":"Test",
        "company":"webertela",
        "address_1":"215 Nutsubidze str.",
        "address_2":"215 - 2 - 1",
        "city":"Nutsubidze",
        "state":"tbilisi",
        "postcode":"0186",
        "country":"GE",
        "email":"levan.andguladze@gmail.com",
        "phone":"577230988"},
    "shipping":{"first_name":"Test",
        "last_name":"Test",
        "company":"webertela",
        "address_1":"215 Nutsubidze str.",
        "address_2":"215 - 2 - 1",
        "city":"Nutsubidze",
        "state":"tbilisi",
        "postcode":"0186",
        "country":"GE"},
    "payment_method":"cop",
    "payment_method_title":"Cash or card  on pickup",
    "transaction_id":"",     "date_paid":null,
    "date_paid_gmt":null,     "date_completed":null,
    "date_completed_gmt":null,     "cart_hash":"dec61e24b102dae5871ae78691391f15",
    "meta_data":[
    {
        "id":37016,
        "key":"is_vat_exempt",
        "value":"no"}
    ],
    "line_items":[
    {
        "id":782,
        "name":"Papa Ronny",
        "product_id":15039,
        "variation_id":15070,
        "quantity":1,
        "tax_class":"",
        "subtotal":"18.20",
        "subtotal_tax":"0.00",
        "total":"18.20",
        "total_tax":"0.00",
        "taxes":[],
        "meta_data":[
        {
            "id":7650,
            "key":"pa_size",
            "value":"medium"
        },
        {"id":7651,
            "key":"pa_crust",
            "value":"original-crust"},
        {"id":7652,     "key":"sauce",
            "value":"Original Sauce"}],
        "sku":"",     "price":18.2},
    {"id":783,     "name":"Driftin'",     "product_id":15133,     "variation_id":15147,     "quantity":1,
        "tax_class":"",     "subtotal":"24.30",     "subtotal_tax":"0.00",     "total":"24.30",
        "total_tax":"0.00",     "taxes":[],     "meta_data":[{"id":7662,     "key":"pa_size",     "value":"medium"},
        {"id":7663,     "key":"pa_crust",     "value":"original-crust"},     {"id":7664,     "key":"sauce",
        "value":"Original Sauce"}],     "sku":"",     "price":24.3}],
    "tax_lines":[],
    "shipping_lines":[{"id":784,     "method_title":"Local pickup Saburtalo",
        "method_id":"local_pickup",     "instance_id":"4",     "total":"0.00",     "total_tax":"0.00",     "taxes":[],
        "meta_data":[{"id":7670a,
            "key":"Items",
            "value":"Papa Ronny &times; 1,
               Driftin' &times; 1"}]}],     "fee_lines":[],     "coupon_lines":[],     "refunds":[],     "currency_symbol":"?",     "_links":{"self":[{"href":"https://www.ronnys.ge/wp-json/wc/v3/orders/16557"}],     "collection":[{"href":"https://www.ronnys.ge/wp-json/wc/v3/orders"}],     "customer":[{"href":"https://www.ronnys.ge/wp-json/wc/v3/customers/1"}]}}{"id":16560,     "parent_id":0,     "number":"16560",     "order_key":"wc_order_lGnEK0AlRlFGT",     "created_via":"checkout",     "version":"4.0.1",     "status":"on-hold",     "currency":"GEL",     "date_created":"2020-05-01T15:30:14",     "date_created_gmt":"2020-05-01T11:30:14",     "date_modified":"2020-05-01T15:30:15",     "date_modified_gmt":"2020-05-01T11:30:15",     "discount_total":"0.00",     "discount_tax":"0.00",     "shipping_total":"0.00",     "shipping_tax":"0.00",     "cart_tax":"0.00",     "total":"36.40",     "total_tax":"0.00",     "prices_include_tax":true,     "customer_id":0,     "customer_ip_address":"176.221.239.92",     "customer_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,      like Gecko) Chrome/81.0.4044.129 Safari/537.36",     "customer_note":"",     "billing":{"first_name":"test",     "last_name":"test",     "company":"",     "address_1":"asdasdasd",     "address_2":"CO GLOBAL TRANSPORTER GT32627",     "city":"asdasd",     "state":"asdasd",     "postcode":"0180",     "country":"GE",     "email":"asdasdasds@as.ge",     "phone":"577758595"},     "shipping":{"first_name":"test",     "last_name":"test",     "company":"",     "address_1":"asdasdasd",     "address_2":"CO GLOBAL TRANSPORTER GT32627",     "city":"asdasd",     "state":"asdasd",     "postcode":"0180",     "country":"GE"},     "payment_method":"cop",     "payment_method_title":"Cash or card  on pickup",     "transaction_id":"",     "date_paid":null,     "date_paid_gmt":null,     "date_completed":null,     "date_completed_gmt":null,     "cart_hash":"96bf3f66f8af42511632c23a025be991",     "meta_data":[{"id":37139,     "key":"is_vat_exempt",     "value":"no"}],     "line_items":[{"id":790,     "name":"Papa Ronny",     "product_id":15039,     "variation_id":15070,     "quantity":2,     "tax_class":"",     "subtotal":"36.40",     "subtotal_tax":"0.00",     "total":"36.40",     "total_tax":"0.00",     "taxes":[],     "meta_data":[{"id":7728,     "key":"pa_size",     "value":"medium"},     {"id":7729,     "key":"pa_crust",     "value":"original-crust"},     {"id":7730,     "key":"sauce",     "value":"Original Sauce"}],     "sku":"",     "price":18.2}],     "tax_lines":[],     "shipping_lines":[{"id":791,     "method_title":"Local pickup Saburtalo",     "method_id":"local_pickup",     "instance_id":"4",     "total":"0.00",     "total_tax":"0.00",     "taxes":[],     "meta_data":[{"id":7736,     "key":"Items",     "value":"Papa Ronny &times; 2"}]}],     "fee_lines":[],     "coupon_lines":[],     "refunds":[],     "currency_symbol":"?",     "_links":{"self":[{"href":"https://www.ronnys.ge/wp-json/wc/v3/orders/16560"}],     "collection":[{"href":"https://www.ronnys.ge/wp-json/wc/v3/orders"}]}}